ALTER TABLE "stock_balances" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "stock_ledgers" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "stock_balances" CASCADE;--> statement-breakpoint
DROP TABLE "stock_ledgers" CASCADE;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "total_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "check_in_lat" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "check_in_lng" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "check_out_lat" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "check_out_lng" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "attendance" ALTER COLUMN "adjusted_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "bom_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_required" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_ordered" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_received" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "costs" ALTER COLUMN "amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "delivery_note_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "employee_salary_components" ALTER COLUMN "amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "ordered_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "received_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "accepted_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "rejected_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_balances" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_balances" ALTER COLUMN "reserved_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_balances" ALTER COLUMN "available_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_balances" ALTER COLUMN "unit_cost" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "unit_cost" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "total_cost" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "journal_entries" ALTER COLUMN "total_debit" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "journal_entries" ALTER COLUMN "total_credit" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "journal_entry_lines" ALTER COLUMN "debit" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "journal_entry_lines" ALTER COLUMN "credit" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_balances" ALTER COLUMN "total_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_balances" ALTER COLUMN "carry_over_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_balances" ALTER COLUMN "used_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_balances" ALTER COLUMN "pending_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_requests" ALTER COLUMN "total_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "leave_requests" ALTER COLUMN "total_days" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "leave_types" ALTER COLUMN "max_days_per_year" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "material_consumptions" ALTER COLUMN "planned_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "material_consumptions" ALTER COLUMN "actual_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "material_consumptions" ALTER COLUMN "scrap_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "material_consumptions" ALTER COLUMN "waste_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "stock_qty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "min_stock" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "official_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "basic_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "regular_worked_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "paid_leave_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "evening_ot_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "night_ot_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "sunday_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "sunday_night_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "holiday_days_off" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "holiday_worked_weekday_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "holiday_worked_sunday_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "unpaid_leave_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "absent_days" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "attendance_allowance" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "total_late_early_mins" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "gross_earnings" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "total_deductions" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "net_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "bhxh_employee" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "bhxh_employer" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "advance_deduction" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "other_deductions" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "overtime_requests" ALTER COLUMN "total_hours" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "qty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "total" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_orders" ALTER COLUMN "planned_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_orders" ALTER COLUMN "completed_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "production_outputs" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "project_costs" ALTER COLUMN "amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "contract_value" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "target_material_cost" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "target_labor_cost" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "tax_rate" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "tax_amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "line_total" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "received_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "invoiced_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "subtotal" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "tax" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "total" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchase_request_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quote_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quote_items" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quote_items" ALTER COLUMN "total_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quotes" ALTER COLUMN "total_amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "routing_steps" ALTER COLUMN "estimated_minutes" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "salary_profiles" ALTER COLUMN "base_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "sales_orders" ALTER COLUMN "total_amount" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "scrap_logs" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoice_items" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoice_items" ALTER COLUMN "unit_price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoice_items" ALTER COLUMN "line_total" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoices" ALTER COLUMN "subtotal" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoices" ALTER COLUMN "tax" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_invoices" ALTER COLUMN "total" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "supplier_prices" ALTER COLUMN "price" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "official_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "basic_salary" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "work_logs" ALTER COLUMN "hours_worked" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "work_orders" ALTER COLUMN "planned_quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "work_orders" ALTER COLUMN "completed_quantity" SET DATA TYPE double precision;