ALTER TABLE "bom_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_required" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_ordered" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "boq_items" ALTER COLUMN "qty_received" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "costs" ALTER COLUMN "amount" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "delivery_note_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "employee_salary_components" ALTER COLUMN "amount" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "ordered_quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "goods_receipt_items" ALTER COLUMN "received_quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "inventory_balances" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "journal_entry_lines" ALTER COLUMN "debit" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "journal_entry_lines" ALTER COLUMN "credit" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "stock_qty" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "min_stock" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "official_salary" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "basic_salary" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "attendance_allowance" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "gross_earnings" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "total_deductions" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "net_salary" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "bhxh_employee" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "monthly_payroll" ALTER COLUMN "bhxh_employer" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "qty" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "production_bom_lines" ALTER COLUMN "total" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "production_outputs" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "project_costs" ALTER COLUMN "amount" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "contract_value" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "target_material_cost" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "target_labor_cost" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "purchase_order_items" ALTER COLUMN "received_quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "purchase_orders" ALTER COLUMN "total" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "purchase_request_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "quote_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "quote_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "scrap_logs" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "supplier_invoice_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(18, 4);--> statement-breakpoint
ALTER TABLE "supplier_invoice_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "supplier_invoices" ALTER COLUMN "total" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "supplier_prices" ALTER COLUMN "price" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "official_salary" SET DATA TYPE numeric(20, 2);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "basic_salary" SET DATA TYPE numeric(20, 2);