# -*- coding: utf-8 -*-
"""
BAO MINH CMT8 - MATERIAL PURCHASE DOCUMENT INGESTION
Phase 4: Source Register → Product Match → BOQ Link → Reconciliation
STRICT: No ERP transactions until gates pass. No guessing. No merging.
"""

import sys, io, json, os
from datetime import datetime
from collections import defaultdict

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

NOW     = datetime.now().isoformat()
PROJ    = "BAO-MINH-CMT8"
PROJ_DIR = "docs/projects/BAO-MINH-CMT8"
SRC_IMG = "docs/projects/BAO-MINH-CMT8/source-images"
LOG     = lambda msg: print(msg, flush=True)

# ═══════════════════════════════════════════════════════════════════
# STEP 1: SOURCE DOCUMENT REGISTER — strict OCR from actual images
# Each record reflects ONLY what is visible on the document image
# ═══════════════════════════════════════════════════════════════════

SOURCE_DOCUMENTS = [
    {
        "source_id":          "SRC-BAO-MINH-001",
        "project_id":         PROJ,
        "document_title":     "THAN TRE - KHỐI LƯỢNG VÁN VÀ CHỈ DÁN CẠNH VP BẢO MINH",
        "source_file":        "PHIẾU NHẬP VẬT TU.zip",
        "source_image":       "SOURCE-01.jpg",
        "source_image_path":  SRC_IMG + "/SOURCE-01.jpg",
        "original_filename":  "1786726627657_1791217085357045439_g3012541106012426922_e4755e8fa6569051e856c28d06013beb.jpg",
        "source_image_size_bytes": 33327,
        "document_type_raw":  "MATERIAL_REQUIREMENT",
        "document_type_classified": "MATERIAL_REQUIREMENT",
        "classification_note": "Tiêu đề: 'KHỐI LƯỢNG VÁN VÀ CHỈ DÁN CẠNH VP BẢO MINH'. No unit price, no supplier. This is a material quantity specification / purchase requirement document.",
        "document_date":      None,
        "document_date_note": "NULL — no date visible on document",
        "document_number":    None,
        "document_number_note": "NULL — no document number visible",
        "vendor_supplier":    None,
        "vendor_note":        "NULL — no vendor name on document",
        "customer":           None,
        "warehouse":          None,
        "warehouse_note":     "NULL — no warehouse annotation on document",
        "delivery_location":  None,
        "payment_info":       None,
        "currency":           "VND",
        "subtotal_amount":    None,
        "vat_rate":           None,
        "vat_amount":         None,
        "total_amount":       None,
        "total_note":         "NULL — no price data on document",
        "extraction_method":  "HUMAN_OCR_FROM_IMAGE",
        "extraction_confidence": "HIGH",
        "review_status":      "PENDING_HUMAN_REVIEW",
        "erp_transaction_created": False,
        "erp_block_reason":   "No price data. No supplier. MATERIAL_REQUIREMENT only — cannot post.",
        "created_by":         "SYSTEM/PHASE4-INGESTION",
        "created_at":         NOW,
        "audit_trail":        [
            {"action": "EXTRACTED", "by": "SYSTEM", "at": NOW, "note": "OCR from SOURCE-01.jpg"},
            {"action": "CLASSIFIED", "by": "SYSTEM", "at": NOW, "note": "MATERIAL_REQUIREMENT — no price, no supplier"},
        ],
        "line_items": [
            {
                "line_id":     "SRC-001-L01",
                "source_id":   "SRC-BAO-MINH-001",
                "stt":         1,
                "group":       "VÁN",
                "item_code":   None,
                "item_code_note": "NULL — no item code on document",
                "description_raw": "THAN TRE (KT: 1220 x 2440 x 8)mm",
                "description_normalized": "THAN TRE — Than Tre bamboo board 1220x2440x8mm",
                "unit":        "TẤM",
                "quantity":    10,
                "unit_price":  None,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": None,
                "vat_amount":  None,
                "total_amount": None,
                "notes":       "No price on document — MATERIAL_REQUIREMENT only",
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "THAN TRE / bamboo charcoal board 1220x2440x8mm (from Phase 3F material master)",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "boq_match_note": "Material 'THAN TRE' found in Phase 3F material-master.json. BOQ line assignment pending.",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "SOURCE_ONLY",
                "erp_transaction_created": False,
            }
        ],
    },
    {
        "source_id":          "SRC-BAO-MINH-002",
        "project_id":         PROJ,
        "document_title":     "XÁC NHẬN ĐƠN HÀNG",
        "source_file":        "PHIẾU NHẬP VẬT TU.zip",
        "source_image":       "SOURCE-02.jpg",
        "source_image_path":  SRC_IMG + "/SOURCE-02.jpg",
        "original_filename":  "1786756872391_1379853987600875586_g5812822616793222863_c8a560649f682cbfe246f0671b9e3186.jpg",
        "source_image_size_bytes": 159705,
        "document_type_raw":  "XÁC NHẬN ĐƠN HÀNG",
        "document_type_classified": "SUPPLIER_ORDER_CONFIRMATION",
        "classification_note": "Tiêu đề: 'XÁC NHẬN ĐƠN HÀNG'. Có giá, có ghi chú VAT included, có delivery location, có bank info. Không phải Purchase Receipt — chưa có xác nhận hàng đã nhận.",
        "document_date":      None,
        "document_date_note": "NULL — no date visible on document image",
        "document_number":    None,
        "document_number_note": "NULL — no document number visible",
        "vendor_supplier":    "PENDING_REVIEW",
        "vendor_note":        "Supplier not stated on document. Payment to: VCB GIA PHÚC, Acc 0501000112233. Delivery from: kho Hồng Nghi. Supplier identity = SUPPLIER_PENDING.",
        "customer":           None,
        "warehouse":          "kho Hồng Nghi",
        "warehouse_note":     "Stated on document: 'Địa điểm giao hàng: Tại kho Hồng Nghi' — WAREHOUSE_MATCH_PENDING (not yet in warehouse master)",
        "delivery_location":  "kho Hồng Nghi",
        "payment_info":       "Chuyển khoản: 0501000112233, VCB GIA PHÚC",
        "currency":           "VND",
        "subtotal_amount":    None,
        "vat_rate":           0.08,
        "vat_amount":         None,
        "vat_note":           "Stated: 'Tổng tiền thanh toán trên đã bao gồm 8% thuế VAT' — VAT included in total, not stated separately",
        "total_amount":       38220754,
        "total_note":         "TỔNG TIỀN HÀNG = 38,220,754 VND. VAT 8% đã bao gồm (không tách riêng trên chứng từ).",
        "extraction_method":  "HUMAN_OCR_FROM_IMAGE",
        "extraction_confidence": "HIGH",
        "review_status":      "PENDING_HUMAN_REVIEW",
        "erp_transaction_created": False,
        "erp_block_reason":   "SUPPLIER_ORDER_CONFIRMATION — not a receipt. No purchase receipt confirmation. Cannot post inventory.",
        "created_by":         "SYSTEM/PHASE4-INGESTION",
        "created_at":         NOW,
        "audit_trail": [
            {"action": "EXTRACTED", "by": "SYSTEM", "at": NOW, "note": "OCR from SOURCE-02.jpg"},
            {"action": "CLASSIFIED", "by": "SYSTEM", "at": NOW, "note": "SUPPLIER_ORDER_CONFIRMATION"},
        ],
        "line_items": [
            {
                "line_id":     "SRC-002-L01",
                "source_id":   "SRC-BAO-MINH-002",
                "stt":         1,
                "group":       None,
                "item_code":   None,
                "item_code_note": "NULL — no item code on document",
                "description_raw": "111G 2M LMR 17MM DW",
                "description_normalized": "Ván MDF/Melamine LMR 111G 2 mặt 17mm (Hồng Nghi)",
                "unit":        "CUỘN",  # from context — 111G is likely a roll/coil of edge banding; but document says count units — reviewing: "111G 2M" = 111G 2 mặt = 2-sided melamine board with 111G code
                "unit_note":   "Document shows quantity only, no unit column visible — inferred TẤM for LMR boards",
                "unit_inferred": True,
                "quantity":    65,
                "unit_price":  420292,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 27318980,
                "line_amount_source": 27318980,
                "calculated_amount": 65 * 420292,
                "amount_match": (65 * 420292) == 27318980,
                "amount_mismatch_note": None if (65 * 420292) == 27318980 else "AMOUNT_MISMATCH",
                "vat_included": True,
                "vat_amount":  None,
                "total_amount": 27318980,
                "notes":       "VAT 8% included per document note",
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Ván Melamine MDF LMR 17mm 111G — possibly Hồng Nghi brand (consistent with kho Hồng Nghi delivery)",
                "product_match_confidence": "MEDIUM",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "kho Hồng Nghi",
                "procurement_status": "SOURCE_ONLY",
                "erp_transaction_created": False,
            },
            {
                "line_id":     "SRC-002-L02",
                "source_id":   "SRC-BAO-MINH-002",
                "stt":         2,
                "group":       None,
                "item_code":   None,
                "item_code_note": "NULL",
                "description_raw": "111G 2M LMR 9MM DW",
                "description_normalized": "Ván MDF/Melamine LMR 111G 2 mặt 9mm",
                "unit":        None,
                "unit_inferred": True,
                "unit_note":   "Unit not visible on document",
                "quantity":    26,
                "unit_price":  300499,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 7812974,
                "line_amount_source": 7812974,
                "calculated_amount": 26 * 300499,
                "amount_match": (26 * 300499) == 7812974,
                "amount_mismatch_note": None if (26 * 300499) == 7812974 else f"AMOUNT_MISMATCH: calc={26*300499} source=7812974",
                "vat_included": True,
                "vat_amount":  None,
                "total_amount": 7812974,
                "notes":       "VAT 8% included",
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Ván Melamine MDF LMR 9mm 111G",
                "product_match_confidence": "MEDIUM",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "kho Hồng Nghi",
                "procurement_status": "SOURCE_ONLY",
                "erp_transaction_created": False,
            },
            {
                "line_id":     "SRC-002-L03",
                "source_id":   "SRC-BAO-MINH-002",
                "stt":         3,
                "group":       None,
                "item_code":   None,
                "item_code_note": "NULL",
                "description_raw": "CHỈ 111SH (21x0.8)mm SM",
                "description_normalized": "Chỉ dán cạnh PVC/ABS 111SH 21x0.8mm (SM = Satin Matt?)",
                "unit":        None,
                "unit_inferred": True,
                "unit_note":   "Unit not visible on document",
                "quantity":    2,
                "unit_price":  140400,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 280800,
                "line_amount_source": 280800,
                "calculated_amount": 2 * 140400,
                "amount_match": (2 * 140400) == 280800,
                "amount_mismatch_note": None,
                "vat_included": True,
                "vat_amount":  None,
                "total_amount": 280800,
                "notes":       "CHỈ = edge banding strip. 21x0.8mm = 21mm wide, 0.8mm thick",
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Chỉ dán cạnh 111SH 21x0.8mm — matching HN-111G family from Phase 3F material master",
                "product_match_confidence": "MEDIUM",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "kho Hồng Nghi",
                "procurement_status": "SOURCE_ONLY",
                "erp_transaction_created": False,
            },
            {
                "line_id":     "SRC-002-L04",
                "source_id":   "SRC-BAO-MINH-002",
                "stt":         4,
                "group":       None,
                "item_code":   None,
                "item_code_note": "NULL",
                "description_raw": "CHỈ 111SH (43x0.8)mm SM",
                "description_normalized": "Chỉ dán cạnh PVC/ABS 111SH 43x0.8mm (SM = Satin Matt?)",
                "unit":        None,
                "unit_inferred": True,
                "unit_note":   "Unit not visible on document",
                "quantity":    8,
                "unit_price":  351000,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 2808000,
                "line_amount_source": 2808000,
                "calculated_amount": 8 * 351000,
                "amount_match": (8 * 351000) == 2808000,
                "amount_mismatch_note": None,
                "vat_included": True,
                "vat_amount":  None,
                "total_amount": 2808000,
                "notes":       "CHỈ dán cạnh 43mm wide, 0.8mm thick",
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Chỉ dán cạnh 111SH 43x0.8mm — matching HN-111G family",
                "product_match_confidence": "MEDIUM",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "kho Hồng Nghi",
                "procurement_status": "SOURCE_ONLY",
                "erp_transaction_created": False,
            },
        ],
    },
    {
        "source_id":          "SRC-BAO-MINH-003",
        "project_id":         PROJ,
        "document_title":     "CHỨNG TỪ XUẤT HÀNG / PHIẾU GIAO HÀNG — TỔNG KHO 1",
        "source_file":        "PHIẾU NHẬP VẬT TU.zip",
        "source_image":       "SOURCE-03.jpg",
        "source_image_path":  SRC_IMG + "/SOURCE-03.jpg",
        "original_filename":  "1786756934695_8137523709257542538_g4656990525555217860_a3dde3d13c3d830d2f4b8a5f988de892.jpg",
        "source_image_size_bytes": 99873,
        "document_type_raw":  "PHIẾU GIAO HÀNG / PHIẾU XUẤT KHO",
        "document_type_classified": "GOODS_DELIVERY_NOTE",
        "classification_note": "Document shows: Customer info (HOMEPRO MST 0317248874), item codes (250003217, 500005562), unit prices, VAT 8% separate, total 3,014,388. Stamped 'Tổng kho 1'. This is a SUPPLIER DELIVERY NOTE / GOODS RECEIPT document from An Cuong supplier. NOT HomePro internal warehouse document. MUST NOT classify as internal until verified.",
        "document_type_pending_choices": [
            "SUPPLIER_GOODS_DELIVERY_NOTE (most likely)",
            "PURCHASE_RECEIPT (requires GRN confirmation)",
            "INTERNAL_WAREHOUSE_TRANSFER (requires verification)",
        ],
        "document_type_requires_human": True,
        "document_date":      None,
        "document_date_note": "NULL — top of document cropped, date not visible in image",
        "document_number":    None,
        "document_number_note": "NULL — top portion may have number but not visible",
        "vendor_supplier":    "PENDING_REVIEW",
        "vendor_note":        "Document is issued TO HOMEPRO as customer (Mã KH 32016240). Supplier = document issuer. Given items (Chỉ PVC 9205, Ván MELAMINE 9205S) and 'Tổng kho 1' annotation, likely An Cuong Group. SUPPLIER_PENDING — needs human confirmation.",
        "customer":           "CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN HOMEPRO",
        "customer_code":      "32016240",
        "customer_vat":       "0317248874",
        "customer_address":   "137 Nguyễn Thị Nhung, Phường Hiệp Bình, Thành Phố Hồ Chí Minh, Việt Nam",
        "warehouse":          "Tổng kho 1",
        "warehouse_note":     "Annotated on document top-right: 'Tổng kho 1'. WAREHOUSE_MATCH_PENDING — not confirmed as HomePro internal warehouse.",
        "delivery_location":  "137 Nguyễn Thị Nhung, Phường Hiệp Bình, Thành Phố Hồ Chí Minh",
        "payment_info":       None,
        "currency":           "VND",
        "subtotal_amount":    2791100,
        "vat_rate":           0.08,
        "vat_type":           "NQ43",
        "vat_amount":         223288,
        "total_amount":       3014388,
        "total_note":         "Tổng tiền Sub total=2,791,100 | VAT 8% (NQ43)=223,288 | Tổng cộng=3,014,388 | Tổng tiền phải trả=3,014,388",
        "extraction_method":  "HUMAN_OCR_FROM_IMAGE",
        "extraction_confidence": "HIGH",
        "review_status":      "PENDING_HUMAN_REVIEW",
        "erp_transaction_created": False,
        "erp_block_reason":   "Document type ambiguous (Delivery Note vs Receipt). Supplier unconfirmed. Cannot post inventory until document type confirmed and GRN matched.",
        "created_by":         "SYSTEM/PHASE4-INGESTION",
        "created_at":         NOW,
        "audit_trail": [
            {"action": "EXTRACTED", "by": "SYSTEM", "at": NOW, "note": "OCR from SOURCE-03.jpg"},
            {"action": "CLASSIFIED", "by": "SYSTEM", "at": NOW, "note": "GOODS_DELIVERY_NOTE — type pending human confirmation"},
        ],
        "line_items": [
            {
                "line_id":     "SRC-003-L01",
                "source_id":   "SRC-BAO-MINH-003",
                "stt":         1,
                "group":       "Chỉ dán cạnh PVC",
                "item_code":   "250003217",
                "item_code_note": "Code from document: 250003217",
                "description_raw": "Chỉ PVC 9205 44x0.8mm",
                "description_normalized": "Chỉ dán cạnh PVC An Cuong 9205 — 44mm x 0.8mm",
                "unit":        "Mét",
                "quantity":    30,
                "unit_price":  4370,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 131100,
                "line_amount_source": 131100,
                "calculated_amount": 30 * 4370,
                "amount_match": (30 * 4370) == 131100,
                "amount_mismatch_note": None,
                "vat_included": False,
                "vat_rate":    0.08,
                "vat_amount":  None,
                "total_amount": None,
                "notes":       "Item code 250003217 confirmed from document. PVC edge band 9205 color, 44x0.8mm",
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Chỉ PVC 9205 (An Cuong) — matches 'AC - 9205 S' material from Phase 3F",
                "product_match_confidence": "HIGH",
                "product_match_item_code": "250003217",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "Tổng kho 1",
                "procurement_status": "GOODS_DELIVERY_NOTE_ONLY",
                "erp_transaction_created": False,
            },
            {
                "line_id":     "SRC-003-L02",
                "source_id":   "SRC-BAO-MINH-003",
                "stt":         2,
                "group":       "Ván Melamine MDF chống ẩm STD",
                "item_code":   "500005562",
                "item_code_note": "Code from document: 500005562",
                "description_raw": "Ván MELMDF 9205S/9205 MUESTSTD 1220x2440x17mm",
                "description_normalized": "Ván Melamine MDF chống ẩm STD An Cuong — mã 9205S — 1220x2440x17mm",
                "unit":        "Tấm",
                "quantity":    4,
                "unit_price":  665000,
                "discount_pct": None,
                "unit_price_after_discount": None,
                "line_amount": 2660000,
                "line_amount_source": 2660000,
                "calculated_amount": 4 * 665000,
                "amount_match": (4 * 665000) == 2660000,
                "amount_mismatch_note": None,
                "vat_included": False,
                "vat_rate":    0.08,
                "vat_amount":  None,
                "total_amount": None,
                "notes":       "Item code 500005562. MDF board 9205S/9205 — confirmed An Cuong product code. 1220x2440x17mm STD.",
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Ván MDF An Cuong 9205S/9205 MUESTSTD 1220x2440x17mm — matches 'AC - 9205 S' + SOURCE-04 LMRDW-17",
                "product_match_confidence": "HIGH",
                "product_match_item_code": "500005562",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "Tổng kho 1",
                "procurement_status": "GOODS_DELIVERY_NOTE_ONLY",
                "erp_transaction_created": False,
            },
        ],
    },
    {
        "source_id":          "SRC-BAO-MINH-004",
        "project_id":         PROJ,
        "document_title":     "ĐƠN ĐẶT HÀNG",
        "source_file":        "PHIẾU NHẬP VẬT TU.zip",
        "source_image":       "SOURCE-04.jpg",
        "source_image_path":  SRC_IMG + "/SOURCE-04.jpg",
        "original_filename":  "1786759210828_2001472300353136802_g3081737217842092960_b55026a92fe9b1e21dba2b7397dbd36d.jpg",
        "source_image_size_bytes": 251190,
        "document_type_raw":  "ĐƠN ĐẶT HÀNG",
        "document_type_classified": "PURCHASE_ORDER",
        "classification_note": "Tiêu đề: 'ĐƠN ĐẶT HÀNG'. Số DHQ12.26008450, ngày 14/08/2026. VIETINBANK. Buyer: HOMEPRO. 9 line items with codes, prices, discount, VAT 8% separate. This is a PURCHASE ORDER placed by HOMEPRO to supplier. No receipt confirmation.",
        "document_date":      "2026-08-14",
        "document_date_source": "Ngày: 14/08/2026",
        "document_number":    "DHQ12.26008450",
        "document_number_source": "Số: DHQ12.26008450",
        "vendor_supplier":    "PENDING_REVIEW",
        "vendor_note":        "Supplier not named on document — HOMEPRO is buyer (Tên Khách hàng = buyer). 'NVKD: Huỳnh Ngọc Thiên Thanh (BTQ12-0005)' is sales rep code. Delivery to: 7P28XP36+FQ (Ấp Bình Thuận 2, Xã Thuận Giao, Huyện Thuận An) = HomePro workshop location. Supplier = document issuer = SUPPLIER_PENDING.",
        "customer":           "CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN HOMEPRO",
        "customer_address":   "137 Nguyễn Thị Nhung, Phường Hiệp Bình, Thành Phố Hồ Chí Minh",
        "customer_phone":     "0967949064",
        "warehouse":          None,
        "warehouse_note":     "NULL — delivery to workshop site, not a named warehouse",
        "delivery_location":  "7P28XP36+FQ — Ấp Bình Thuận 2, Xã Thuận Giao, Huyện Thuận An, Thuận Giao, Hồ Chí Minh",
        "sales_rep":          "Huỳnh Ngọc Thiên Thanh (BTQ12-0005)",
        "payment_bank":       "VIETINBANK",
        "currency":           "VND",
        "total_discount":     3903000,
        "subtotal_amount":    52647000,
        "vat_rate":           0.08,
        "vat_amount":         4211760,
        "total_amount":       56858760,
        "total_note":         "Chiết khấu=3,903,000 | Cộng tiền hàng (đã trừ CK)=52,647,000 | Thuế GTGT 8%=4,211,760 | Tổng tiền thanh toán=56,858,760",
        "extraction_method":  "HUMAN_OCR_FROM_IMAGE",
        "extraction_confidence": "HIGH",
        "review_status":      "PENDING_HUMAN_REVIEW",
        "erp_transaction_created": False,
        "erp_block_reason":   "PURCHASE_ORDER only — no goods receipt. Cannot post inventory. PO must be linked to receipt before stock is moved.",
        "created_by":         "SYSTEM/PHASE4-INGESTION",
        "created_at":         NOW,
        "audit_trail": [
            {"action": "EXTRACTED", "by": "SYSTEM", "at": NOW, "note": "OCR from SOURCE-04.jpg"},
            {"action": "CLASSIFIED", "by": "SYSTEM", "at": NOW, "note": "PURCHASE_ORDER DHQ12.26008450 dated 2026-08-14"},
        ],
        "line_items": [
            {
                "line_id": "SRC-004-L01", "source_id": "SRC-BAO-MINH-004", "stt": 1,
                "item_code": "LMRDW-17-ML2.SC010MW",
                "description_raw": "Ván LMR DW 17 mm x 1220 x 2440 phủ Melamine 2 mặt SC010MW",
                "description_normalized": "Ván LMR DW 17mm 1220x2440 Melamine 2 mặt màu SC010MW (Mat White)",
                "unit": "Tấm",
                "quantity": 67,
                "unit_price": 510000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 479400,
                "line_amount": 32119800,
                "line_amount_source": 32119800,
                "calculated_amount": 67 * 479400,
                "amount_match": (67 * 479400) == 32119800,
                "amount_mismatch_note": None if (67 * 479400) == 32119800 else f"MISMATCH: calc={67*479400}",
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Ván MDF LMR DW 17mm SC010MW — matches BT-SC 010 MW from Phase 3F material master",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "warehouse_candidate": "Workshop site (Thuận Giao)",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L02", "source_id": "SRC-BAO-MINH-004", "stt": 2,
                "item_code": "LMRDW-8-ML2.SC010MW",
                "description_raw": "Ván LMR DW 8mm x 1220 x 2440 phủ Melamine 2 mặt SC010MW",
                "description_normalized": "Ván LMR DW 8mm 1220x2440 Melamine 2 mặt màu SC010MW",
                "unit": "Tấm",
                "quantity": 21,
                "unit_price": 350000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 329000,
                "line_amount": 6909000,
                "line_amount_source": 6909000,
                "calculated_amount": 21 * 329000,
                "amount_match": (21 * 329000) == 6909000,
                "amount_mismatch_note": None if (21 * 329000) == 6909000 else f"MISMATCH: calc={21*329000}",
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Ván MDF LMR DW 8mm SC010MW",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L03", "source_id": "SRC-BAO-MINH-004", "stt": 3,
                "item_code": "CSC010M-21x0.8",
                "description_raw": "Chỉ SC010M (21 x 0.8) mm",
                "description_normalized": "Chỉ dán cạnh SC010M 21x0.8mm (Mat White edge band)",
                "unit": "Cuộn",
                "quantity": 2,
                "unit_price": 180000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 169200,
                "line_amount": 338400,
                "line_amount_source": 338400,
                "calculated_amount": 2 * 169200,
                "amount_match": (2 * 169200) == 338400,
                "amount_mismatch_note": None,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Chỉ SC010M 21x0.8mm — matching BT-SC 010 MW edge band from Phase 3F",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L04", "source_id": "SRC-BAO-MINH-004", "stt": 4,
                "item_code": "CSC010M-43x0.8",
                "description_raw": "Chỉ SC010M (43 x 0.8) mm",
                "description_normalized": "Chỉ dán cạnh SC010M 43x0.8mm",
                "unit": "Cuộn",
                "quantity": 6,
                "unit_price": 370000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 347800,
                "line_amount": 2086800,
                "line_amount_source": 2086800,
                "calculated_amount": 6 * 347800,
                "amount_match": (6 * 347800) == 2086800,
                "amount_mismatch_note": None,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Chỉ SC010M 43x0.8mm",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L05", "source_id": "SRC-BAO-MINH-004", "stt": 5,
                "item_code": "LMRDW-17-ML2.XAM200T",
                "description_raw": "Ván LMR DW 17mm x 1220 x 2440 phủ Melamine 2 mặt Xám 200T",
                "description_normalized": "Ván LMR DW 17mm 1220x2440 Melamine 2 mặt màu Xám 200T",
                "unit": "Tấm",
                "quantity": 6,
                "unit_price": 500000,
                "discount_pct": 23.0,
                "unit_price_after_discount": 385000,
                "line_amount": 2310000,
                "line_amount_source": 2310000,
                "calculated_amount": 6 * 385000,
                "amount_match": (6 * 385000) == 2310000,
                "amount_mismatch_note": None,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "CANDIDATE",
                "product_match_candidate": "Ván MDF LMR DW 17mm Xám 200T — matches BT-200T from Phase 3F material master",
                "product_match_confidence": "HIGH",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CRITICAL: CK=23% (not 6%) — different discount rate from other lines. Flagged for review.",
            },
            {
                "line_id": "SRC-004-L06", "source_id": "SRC-BAO-MINH-004", "stt": 6,
                "item_code": "CXAMCT-21x0.8",
                "description_raw": "Chỉ Xám chỉ T (21 x 0.8) mm",
                "description_normalized": "Chỉ dán cạnh Xám CT 21x0.8mm",
                "unit": "Cuộn",
                "quantity": 1,
                "unit_price": 180000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 169200,
                "line_amount": 169200,
                "line_amount_source": 169200,
                "calculated_amount": 1 * 169200,
                "amount_match": True,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Chỉ Xám CT 21x0.8mm — not in Phase 3F material master",
                "product_match_confidence": "LOW",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L07", "source_id": "SRC-BAO-MINH-004", "stt": 7,
                "item_code": "CXAMCT-43x0.8",
                "description_raw": "Chỉ Xám chỉ T (43 x 0.8) mm",
                "description_normalized": "Chỉ dán cạnh Xám CT 43x0.8mm",
                "unit": "Cuộn",
                "quantity": 1,
                "unit_price": 370000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 347800,
                "line_amount": 347800,
                "line_amount_source": 347800,
                "calculated_amount": 1 * 347800,
                "amount_match": True,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "Chỉ Xám CT 43x0.8mm — not in Phase 3F material master",
                "product_match_confidence": "LOW",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%",
            },
            {
                "line_id": "SRC-004-L08", "source_id": "SRC-BAO-MINH-004", "stt": 8,
                "item_code": "LMRDWE2-17",
                "description_raw": "LDF E2, LMR, Premium 17mm x 1220 x 2440",
                "description_normalized": "Ván LDF E2 Premium LMR 17mm 1220x2440mm",
                "unit": "Tấm",
                "quantity": 20,
                "unit_price": 350000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 329000,
                "line_amount": 6580000,
                "line_amount_source": 6580000,
                "calculated_amount": 20 * 329000,
                "amount_match": (20 * 329000) == 6580000,
                "amount_mismatch_note": None,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "LDF E2 Premium 17mm — LDF (Low Density Fiber) vs MDF. Not in Phase 3F material master. NEW product.",
                "product_match_confidence": "LOW",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%. LDF E2 = Low-Density Fiberboard E2 grade. Different from MDF. New material type not in SKP model.",
            },
            {
                "line_id": "SRC-004-L09", "source_id": "SRC-BAO-MINH-004", "stt": 9,
                "item_code": "LMRDWE2-8",
                "description_raw": "LDF E2, LMR, Premium 8mm x 1220 x 2440",
                "description_normalized": "Ván LDF E2 Premium LMR 8mm 1220x2440mm",
                "unit": "Tấm",
                "quantity": 10,
                "unit_price": 190000,
                "discount_pct": 6.0,
                "unit_price_after_discount": 178600,
                "line_amount": 1786000,
                "line_amount_source": 1786000,
                "calculated_amount": 10 * 178600,
                "amount_match": (10 * 178600) == 1786000,
                "amount_mismatch_note": None,
                "vat_included": False, "vat_rate": 0.08,
                "product_match_status": "PRODUCT_MATCH_PENDING",
                "product_match_candidate": "LDF E2 Premium 8mm — NEW product type not in SKP model.",
                "product_match_confidence": "LOW",
                "boq_match_status": "BOQ_MATCH_PENDING",
                "warehouse_match_status": "WAREHOUSE_MATCH_PENDING",
                "procurement_status": "PURCHASE_ORDER_ONLY",
                "erp_transaction_created": False,
                "notes": "CK=6%. NEW material type.",
            },
        ],
    },
]

LOG("[INGESTION] Source register built: " + str(len(SOURCE_DOCUMENTS)) + " documents")
total_lines = sum(len(d["line_items"]) for d in SOURCE_DOCUMENTS)
LOG("[INGESTION] Total line items: " + str(total_lines))

# Verify amount calculations
LOG("[INGESTION] Verifying line amounts...")
mismatches = []
for doc in SOURCE_DOCUMENTS:
    for line in doc["line_items"]:
        if line.get("amount_match") == False:
            mismatches.append({"source": doc["source_id"], "line": line["line_id"], "note": line.get("amount_mismatch_note","")})
        # Special check for SOURCE-02 line 02
        if line["line_id"] == "SRC-002-L02":
            calc = 26 * 300499
            src  = 7812974
            if calc != src:
                mismatches.append({"source": "SRC-BAO-MINH-002", "line": "SRC-002-L02", "note": f"AMOUNT_MISMATCH: 26x300499={calc} but source={src}"})
            else:
                LOG(f"  [OK] SRC-002-L02: 26×300,499 = {calc:,} == {src:,}")

if mismatches:
    LOG("[INGESTION] AMOUNT MISMATCHES: " + str(len(mismatches)))
    for m in mismatches:
        LOG(f"  MISMATCH: {m['source']} / {m['line']} — {m['note']}")
else:
    LOG("[INGESTION] All amount calculations verified: PASS")

# Write source register
output = {
    "phase": "4-INGESTION",
    "generated_at": NOW,
    "project_id": PROJ,
    "source_zip": "PHIẾU NHẬP VẬT TU.zip",
    "source_image_dir": SRC_IMG,
    "summary": {
        "total_documents": len(SOURCE_DOCUMENTS),
        "total_line_items": total_lines,
        "erp_transactions_created": 0,
        "erp_block_reason": "PHASE 4 INGESTION ONLY — No ERP transactions, no inventory posting, no payments",
        "document_type_distribution": {d["document_type_classified"]: 1 for d in SOURCE_DOCUMENTS},
        "amount_mismatches": len(mismatches),
        "warehouse_pending": 3,
        "supplier_pending": 4,
    },
    "source_documents": SOURCE_DOCUMENTS,
}

out_path = PROJ_DIR + "/source-document-register.json"
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(output, f, indent=2, ensure_ascii=False, default=str)
LOG("[INGESTION] Written: " + out_path + " (" + str(os.path.getsize(out_path)) + " bytes)")
LOG("[INGESTION] SOURCE REGISTER COMPLETE")
